export const CATALOG_IMAGE_DIRECTORY: string = 'http://localhost:9090/assets/upload/catalog/' 
export const PRODUCT_IMAGE_DIRECTORY: string = 'http://localhost:9090/assets/upload/product/' 
export const VARIANT_IMAGE_DIRECTORY: string = 'http://localhost:9090/assets/upload/variant/' 
export const ACCOUNT_IMAGE_DIRECTORY: string = 'http://localhost:9090/assets/upload/account/' 
export const SIDE_GUIDE_IMAGE_DIRECTORY: string = 'http://localhost:9090/assets/upload/size_guide/'