package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Product generated by hbm2java
 */

@Data
@Entity
@Table(name = "Product")
public class Product implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_id", unique = true, nullable = false)
	private Integer productId;

	@Column(name = "product_name", nullable = false)
	private String productName;

	@Column(name = "slug", unique = true, nullable = false)
	private String slug;

	@Column(name = "description")
	private String description;

	@Column(name = "active")
	private Boolean active;

	@Column(name = "sale")
	private Boolean sale;

	@Column(name = "[top]")
	private Boolean top;

	@Column(name = "new")
	private Boolean new_;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catalog_id")
	private Catalog catalog;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "planting_difficulty_level_id")
	private PlantingDifficultyLevel plantingDifficultyLevel;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_sale_id")
	private ProductSale productSale;

	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "product_id")
	private ProductCareGuide productCareGuide;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	private Date createdAt;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "image_size_guide_id")
	private Image imageSizeGuide;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	private Date updatedAt;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product", cascade = CascadeType.ALL, orphanRemoval = true)
	private Set<ProductVariant> productVariants = new HashSet<ProductVariant>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product", cascade = CascadeType.REMOVE)
	private Set<CartDetail> cartDetails = new HashSet<CartDetail>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
	@JoinTable(name = "Wishlist", joinColumns = {
			@JoinColumn(name = "product_id", nullable = false, updatable = false) }, inverseJoinColumns = {
			@JoinColumn(name = "account_id", nullable = false, updatable = false) })
	private Set<Account> wishlists = new HashSet<Account>(0);

	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "ProductImage", joinColumns = {
			@JoinColumn(name = "product_id", nullable = false, updatable = false) }, inverseJoinColumns = {
			@JoinColumn(name = "image_id", nullable = false, updatable = false) })
	private Set<Image> images = new HashSet<Image>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product", cascade = CascadeType.REMOVE)
	private Set<ProductReview> productReviews = new HashSet<ProductReview>(0);

	public Product() {
	}

	public Product(Catalog catalog, ProductSale productSale,
			String productName, String description, Boolean active, Boolean sale, Boolean top, Boolean new_,
			Date createdAt, Date updatedAt, Set<ProductVariant> productVariants, Set<CartDetail> cartDetails,
			Set<OrderDetail> orderDetails, Set<Image> images, Set<ProductReview> productReviews) {
		this.catalog = catalog;
		this.productSale = productSale;
		this.productName = productName;
		this.description = description;
		this.active = active;
		this.sale = sale;
		this.top = top;
		this.new_ = new_;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.productVariants = productVariants;
		this.cartDetails = cartDetails;
		this.orderDetails = orderDetails;
		this.images = images;
		this.productReviews = productReviews;
	}

	@Override
	public int hashCode() {
		return Objects.hash(productId);
	}
}
